
owner: goeckslab
categories:
  - Machine Learning
remote_repository_url: https://github.com/goeckslab/Galaxy-ML.git
homepage_url: https://github.com/goeckslab/Galaxy-ML.git
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for Galaxy-ML tool: {{ tool_name }}"
suite:
  name: suite_galaxy_ml
  description: Galaxy-Ml wraps a suite of tools that conduct state-of-the-art machine learnings.  
