version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Build Dependencies
          command: |
            pip install -e .
            pip install flake8 pytest | cat; test ${PIPESTATUS[0]} -eq 0
            mkdir test-reports | cat
      - run:
          name: Flake8
          command: |
            flake8 . --statistics --show-source --ignore=F401,F821,I100,W503 -v
      - run:
          name: Run API Tests
          command: |
            cd ./galaxy_ml
            python -m pytest ./tests -sv
      - store_test_results:
          path: test-reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
